spring: 
  datasource:
    username: concert_venue
    password: concert_venue
    url: jdbc:mysql://localhost:3306/concert_venue
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  sql:
    init:
      mode: never
      